volumes:
  REPLACE-ME-db:
    name: REPLACE-ME-db

services:
  REPLACE-ME:
    container_name: REPLACE-ME
    image: REPLACE-ME
    volumes:
      - ./:/app
    build: .
    restart: unless-stopped
    user: REPLACE-UID:REPLACE-GID
    ports:
      - 5173:5173
      - 4983:4983
    depends_on:
      - REPLACE-ME-db
    environment:
      PUID: REPLACE-UID
      PGID: REPLACE-GID
      DATABASE_URL: ${DATABASE_URL}
  REPLACE-ME-db:
    container_name: REPLACE-ME-db
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - REPLACE-ME-db:/var/lib/postgresql/data
    environment:
      PUID: REPLACE-UID
      PGID: REPLACE-GID
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
