#!/bin/bash

set -xe

cd

export CAN_SUDO=$(sudo true && echo "true" || echo "false")
export PATH=~/bin:~/.local/bin:~/.local/homebrew/bin:/home/linuxbrew/.linuxbrew/bin:$PATH

if [ -S $XDG_RUNTIME_DIR/agent.sock ]; then
    export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/agent.sock
else
    eval $(ssh-agent -t 12h -s -a $XDG_RUNTIME_DIR/agent.sock)
fi
ssh-add

yadm remote set-url origin "git@github.com:nickconway/dotfiles.git"

if command -v termux-reload-settings; then
    apt update -y && apt upgrade -y
    pkg install openssh termux-api gnupg fzf -y
    yadm decrypt
    yadm alt
    exit
fi

if [[ $(yadm config local.class) == "" ]]; then
    read -p "Enter YADM class (q to quit): " YADM_CLASS
    while [[ "$YADM_CLASS" != "q" ]] && [[ "$YADM_CLASS" != "" ]]; do
        yadm config --add local.class $YADM_CLASS
        read -p "Enter another YADM class (q to quit): " YADM_CLASS
    done
fi

export GPG_TTY=$(tty)
yadm decrypt
yadm alt

. ~/.config/shell/common/encrypted.sh

if [[ -e ~/.ssh/authorized_keys ]]; then
    for f in $(ls ~/.ssh/*.pub); do 
        grep -qF "$(cat $f)" ~/.ssh/authorized_keys || echo "$(cat $f)" >> ~/.ssh/authorized_keys
    done
else
    [[ $(ls ~/.ssh/*.pub) ]] && cat ~/.ssh/*.pub >> ~/.ssh/authorized_keys
fi

if [[ $(uname -n) == "steamdeck" ]]; then
    sudo steamos-readonly disable
    echo "keyserver hkps://keyserver.ubuntu.com" >> /etc/pacman.d/gnupg/gpg.conf
    sudo pacman-key --init
    sudo pacman-key --populate
    sudo pacman-key --refresh-keys
    yay -S base-devel
fi

[[ $(ls "$HOME"/.config/gpg) ]] && gpg --import "$HOME"/.config/gpg/*

if [[ $(uname -n) == "steamdeck" ]]; then
    sudo touch /etc/subuid /etc/subgid
    sudo usermod --add-subuid 100000-165535 --add-subgid 100000-165535 $USER
    curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- --prefix ~/.local
    curl -Lo ~/.local/bin/podman https://github.com/89luca89/podman-launcher/releases/latest/download/podman-launcher-amd64
    chmod +x .local/bin/podman
    distrobox create -i ubuntu
fi

install-all

([[ -e ~/.tmux/plugins/tpm ]] || git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins)

mkdir -p ~/.config/zellij/plugins
curl -L "https://github.com/imsnif/multitask/releases/latest/download/multitask.wasm" -o ~/.config/zellij/plugins/multitask.wasm
curl -L "https://github.com/rvcas/room/releases/latest/download/room.wasm" -o ~/.config/zellij/plugins/room.wasm
curl -L "https://github.com/dj95/zjstatus/releases/latest/download/zjstatus.wasm" -o ~/.config/zellij/plugins/zjstatus.wasm

if command -v fc-cache > /dev/null; then
    mkdir -p ~/.local/share/fonts/hack-nerd-font
    wget -O Hack.zip https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hack.zip
    unzip -o Hack.zip -d ~/.local/share/fonts/hack-nerd-font
    fc-cache -fv
    rm -rf Hack.zip
fi

if [[ "$(yadm config --get-all local.class)" != *"work"* ]]; then
    [[ $(gh repo list | awk 'NR!=1' | wc -l) == $(ls ~/git | wc -l) ]] || clone-all
fi

if [[ $CAN_SUDO == "true" ]]; then
    sudo grep "$USER ALL=" /etc/sudoers || sudo bash -c "echo $USER ALL=\(ALL\) NOPASSWD:ALL >> /etc/sudoers"
    sudo grep "session optional pam_exec.so /usr/bin/ntfy-ssh" /etc/pam.d/sshd || sudo bash -c "echo session optional pam_exec.so /usr/bin/ntfy-ssh >> /etc/pam.d/sshd"

    sudo GPG_TTY="$GPG_TTY" SSH_AUTH_SOCK="$SSH_AUTH_SOCK" PATH="$PATH" $(which yadm) --yadm-dir /etc/yadm --yadm-data /etc/yadm/data clone -w / https://github.com/nickconway/dotfiles -f --single-branch --branch sys \
        && sudo GPG_TTY="$GPG_TTY" SSH_AUTH_SOCK="$SSH_AUTH_SOCK" PATH="$PATH" $(which yadm) --yadm-dir /etc/yadm --yadm-data /etc/yadm/data remote set-url origin git@github.com:nickconway/dotfiles.git \
        && sudo GPG_TTY="$GPG_TTY" SSH_AUTH_SOCK="$SSH_AUTH_SOCK" PATH="$PATH" $(which yadm) --yadm-dir /etc/yadm --yadm-data /etc/yadm/data reset --hard \
        && ([[ -e /etc/yadm/encrypt ]] && sudo GPG_TTY="$GPG_TTY" SSH_AUTH_SOCK="$SSH_AUTH_SOCK" PATH="$PATH" $(which yadm) --yadm-dir /etc/yadm --yadm-data /etc/yadm/data decrypt || echo "Does not exist") \
        && sudo GPG_TTY="$GPG_TTY" SSH_AUTH_SOCK="$SSH_AUTH_SOCK" PATH="$PATH" $(which yadm) --yadm-dir /etc/yadm --yadm-data /etc/yadm/data alt

    sudo grep "$(which zsh)" /etc/shells || sudo bash -c "echo $(which zsh) >> /etc/shells"
    sudo chsh $USER -s $(which zsh)
fi

[[ "$(yadm config --get-all local.class)" == *"work"* && "$(yadm config --get-all local.class)" == *"vm"* ]] && . ~/.config/shell/common/work.sh && work-setup

yadm checkout ~/.bash_profile
yadm checkout ~/.bashrc
yadm checkout ~/.zshrc

echo "All done!"

curl -d "Bootstrapping complete on $(hostname)" https://ntfy.conway.dev/notifications -H "Authorization: Bearer ${NTFY_TOKEN}"
