#!/bin/bash

set -xe

export PATH=$PATH:~/bin:~/.local/bin
(sudo grep $USER /etc/sudoers || sudo bash -c "echo $USER ALL=\(ALL\) NOPASSWD:ALL >> /etc/sudoers") || echo "Remove sudo password failed"

yadm remote set-url origin "git@github.com:nickconway/dotfiles.git"

if [[ $(yadm config local.class) == "" ]]; then
    read -p "Enter YADM class: " YADM_CLASS
    yadm config local.class $YADM_CLASS
fi

yadm decrypt
yadm alt

alias sysyadm="yadm --yadm-dir /etc/yadm --yadm-data /etc/yadm/data"
(sudo env "PATH=$PATH" $(alias sysyadm | cut -d\' -f2) clone -w / https://github.com/nickconway/dotfiles -f --single-branch --branch sys \
    && sudo env "PATH=$PATH" $(alias sysyadm | cut -d\' -f2) remote set-url origin git@github.com:nickconway/dotfiles.git \
    && sudo env "PATH=$PATH" $(alias sysyadm | cut -d\' -f2) reset --hard \
    && sudo env "PATH=$PATH" $(alias sysyadm | cut -d\' -f2) alt) || echo "System yadm failed"

if [[ ! -e ~/.local/bin/devbox ]]; then
    curl -fsSLo ~/.local/bin/devbox-install https://get.jetpack.io/devbox && chmod +x ~/.local/bin/devbox-install

    sed -i 's/readonly INSTALL_DIR="\/usr\/local\/bin"/readonly INSTALL_DIR="$HOME\/.local\/bin"/g' ~/.local/bin/devbox-install
    sed -i '/confirm \"Install.*/d' ~/.local/bin/devbox-install
    sed -i 's/$(command -v sudo || true) //g' ~/.local/bin/devbox-install

    devbox-install
    devbox global install
fi

(sudo groupadd docker && sudo usermod -aG docker $USER) || echo "Docker non-root failed"

mkdir -p ~/.config/zellij/plugins
curl -L "https://github.com/imsnif/multitask/releases/latest/download/multitask.wasm" -o ~/.config/zellij/plugins/multitask.wasm
curl -L "https://github.com/rvcas/room/releases/latest/download/room.wasm" -o ~/.config/zellij/plugins/room.wasm

sed -i "/^$/ N; /if \[ -e \/home\/$USER/.nix-profile d" ~/{.zshrc,.bash_profile,.bashrc}

[[ "$(yadm config local.class)" == "work" ]] && work-setup

sudo chsh $USER -s $HOME/.local/share/devbox/global/default/.devbox/virtenv/.wrappers/bin/zsh
