#!/usr/bin/env bash
set -euo pipefail

if [[ -n "${DEBUG_MODE:-}" ]]; then
	set -x
fi

STATE="$(if [[ "$(fuser /dev/video* 2>&1 | wc -l)" -gt 0 ]]; then echo true; else echo false; fi)"
echo "{\"schedule\":\"@every 5s\",\"sensors\":[{\"sensor_name\":\"Webcam Status\",\"sensor_type\":\"binary\",\"sensor_icon\":\"mdi:dice-5\",\"sensor_state\":$STATE}]}"
