#!/bin/env bash

if [[ $(yadm config local.class) != work ]]; then
    set -xe

    export PATH=$PATH:~/.local/bin:~/.local/go/bin
    cd
    git clone https://github.com/cli/cli.git gh-cli
    cd gh-cli

    if [[ $(uname -n) == steamdeck ]]; then
        distrobox enter ubuntu -- bash -c "make install prefix=$HOME/.local"
    else
        make install prefix=$HOME/.local
    fi
    cd
    rm -rf gh-cli

    gh auth login
    yadm restore ~/.config/gh/config.yml
    [[ -e ~/.local/share/gh/extensions/gh-dash ]] && rm -rf ~/.local/share/gh/extensions/gh-dash
    gh extension install dlvhdr/gh-dash
fi
