#!/usr/bin/env bash

sudo yum -y install ninja-build cmake gcc make unzip gettext curl
sudo apt-get install ninja-build gettext cmake unzip curl
cargo install tree-sitter-cli

git clone https://github.com/neovim/neovim
cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
cd -
rm -rf neovim
nvim --headless "+Lazy! sync" +qa
