#!/usr/bin/env bash

sudo yum install -y libevent ncurses libevent-devel ncurses-devel gcc make bison pkg-config
sudo apt install -y libevent ncurses libevent-dev ncurses-dev build-essential gcc make bison pkg-config

cd
git clone https://github.com/tmux/tmux.git
cd tmux
sh autogen.sh
./configure
make && sudo make install
cd
rm -rf tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins
