Bind({ MainMod, "B" }, hl.dsp.focus({ window = "chromium" }))
Bind({ MainMod, "T" }, hl.dsp.focus({ window = "kitty" }))
Bind({ MainMod, "D" }, hl.dsp.focus({ window = "flatpak run dev.vencord.Vesktop" }))
Bind({ MainMod, "M" }, hl.dsp.focus({ window = "thunderbird" }))
Bind({ MainMod, "F" }, hl.dsp.focus({ window = "feishin" }))

hl.workspace_rule({ workspace = "1", monitor = "DP-1", default = true })
hl.workspace_rule({ workspace = "2", monitor = "DP-2", default = true })
hl.workspace_rule({ workspace = "3", monitor = "DP-3", default = true })

hl.on("hyprland.start", function()
    hl.exec_cmd("[workspace 1 silent] chromium")
    hl.exec_cmd("[workspace 2 silent] kitty")
    hl.exec_cmd("[workspace 2 silent] flatpak run dev.vencord.Vesktop")
    hl.exec_cmd("[workspace 2 silent] thunderbird-beta")
    hl.exec_cmd("[workspace 3 silent] feishin --ozone-platform-hint=auto --password-store='kwallet6'")
    hl.exec_cmd("[workspace 3 silent] chromium --app='https://messages.google.com/web'")
    hl.exec_cmd("[workspace 3 silent] flatpak run app.bluebubbles.BlueBubbles")
    hl.exec_cmd("[workspace 3 silent] chromium --app='https://x.com'")
end)
