#!/usr/bin/env bash
set -euo pipefail

if [[ -n "${LOG:-}" ]]; then
    exec &>"/tmp/$(basename "$0").log"
    set -x
fi

if [[ -n "${DEBUG_MODE:-}" ]]; then
    set -x
fi

media metadata --format '󰎇   {{title}} - {{artist}}'
