#!/bin/bash

set -xe

if [[ $(uname -r) == *WSL* ]]; then
    exit
fi

if command -v apt; then
    sudo apt install network-manager
fi

if [[ $(uname -n) == "steamdeck" ]]; then
    git clone https://github.com/tailscale-dev/deck-tailscale.git
    cd deck-tailscale
    sudo bash tailscale.sh
    sudo tailscale up --ssh --accept-routes --operator=deck
    rm -rf deck-tailscale
else
    curl -fsSL https://tailscale.com/install.sh | sh
    sudo tailscale up --ssh --accept-routes
fi

sudo ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf

sudo systemctl enable systemd-resolved --now
sudo systemctl enable NetworkManager --now

sudo systemctl restart systemd-resolved
sudo systemctl restart NetworkManager
sudo systemctl restart tailscaled
