#!/bin/env bash

set -xe

if command -v gh > /dev/null; then
    exit
fi

git clone https://github.com/cli/cli.git gh-cli
cd gh-cli

if [[ $(uname -n) == steamdeck ]]; then
    distrobox enter ubuntu -- bash -c "make install prefix=$HOME/.local"
else
    make install prefix=$HOME/.local
fi
cd
rm -rf gh-cli

gh auth login
yadm restore ~/.config/gh/config.yml
gh extension install dlvhdr/gh-dash
