source = ~/.cache/wal/colors-hyprland.conf

background {
    monitor =
    path = $WALLPAPER
    color = $background
    blur_passes = 0 # 0 disables blurring
    blur_size = 8
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = $background
    inner_color = $backgroundAlpha
    font_color = $foreground
    fade_on_empty = false
    font_family = NotoSans
    placeholder_text = Input Password...
    hide_input = false
    halign = center
    valign = center
    position = 0, 0
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%-I:%M%p")"
    color = $foreground
    font_size = 150
    font_family = JetBrains Mono Nerd Font ExtraBold
    halign = center
    valign = top
    position = 0, -5%
}

# User
label {
    monitor =
    text = cmd[] bash -c 'echo Hi there, ${USER^}'
    color = $foreground
    font_size = 25
    font_family = NotoSans Medium
    halign = center
    valign = center
    position = 0, 5%
}

# Current Song
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/scripts/get-song
    color = $foreground
    font_size = 15
    font_family = NotoSans, Font Awesome 6 Free Solid
    halign = center
    valign = bottom
    position = 0, 5%
}

label {
    monitor =
    text = 
    font_size = 20
    onclick = shutdown
    color = $foreground
    halign = left
    valign = bottom
    position = 1%, 1%
}

label {
    monitor =
    text = 󰒲
    halign = left
    valign = bottom
    font_size = 20
    position = 3%, 1%
    onclick = systemctl suspend
    color = $foreground
}
