general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
    condition_cmd = [[ ! -e /tmp/.inhibit-lock ]]
    condition_retry = 10
}

listener {
    timeout = 600
    on-timeout = systemctl suspend
    condition_cmd = [[ ! -e /tmp/.inhibit-sleep ]]
    condition_retry = 10
}
