[pyprland]
plugins = [
 "expose",
 "fetch_client_menu",
 "lost_windows",
 "magnify",
 "scratchpads",
 "shift_monitors",
 "toggle_special",
 # "workspaces_follow_focus",
 "shortcuts_menu",
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm tmux new -As Scratch"
class = "kitty-dropterm"
size = "80% 60%"
max_size = "100% 100%"
