# Theme Colors
$bg_core: {background.rgba};
$bg_border: {color8};
$fg: {foreground};
$primary: {color9};
$secondary: {color10};
$accent: {color11};
$info: {color12};

# Base font size (all other sizes scale from this)
$base_font_size = 12px
