[General]
Font="Noto Sans"
FontSize="12"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

Background="{wallpaper}"

AnimationDuration="300"
AnimationEasing="OutQuart"

AutoFingerprintOnLoad=true

DateTextColor="{foreground}"
TimeTextColor="{foreground}"

FormBackgroundColor="{background}"

LoginFieldBackgroundColor="{background}"
PasswordFieldBackgroundColor="{background}"

LoginFieldTextColor="{foreground}"
PasswordFieldTextColor="{foreground}"

PlaceholderTextColor="{color8}"

LoginButtonTextColor="{background}"
LoginButtonBackgroundColor="{color9}"

SystemButtonsIconsColor="{foreground}"
EnvironmentButtonTextColor="{foreground}"

DropdownTextColor="{foreground}"
DropdownSelectedTextColor="{background}"
DropdownBackgroundColor="{background}"
DropdownSelectedBackgroundColor="{color9}"
DropdownBorderColor="{color15}"
DropdownSelectedBorderColor="{color15}"

HoverLoginButtonBackgroundColor="{foreground}"
HoverSystemButtonsIconsColor="{color10}"
HoverEnvironmentButtonTextColor="{color10}"

Blur="0.0"
FormPosition="center"
