[meta]
name = "Vicinae Pywal"
description = "Pywal Vicinae"
variant = "dark"
inherits = "vicinae-dark"

[colors.core]
accent = "{color9}"
accent_foreground = "{background}"
background = "{background}"
foreground = "{foreground}"
secondary_background = "{background.lighten(5%)}"
border = "{background}"

[colors.main_window]
border = "{background}"
footer = {{ background = "colors.core.secondary_background" }

[colors.settings_window]
border = "{background}"

[colors.accents]
blue = "#2f6fed"
green = "#3a9c61"
magenta = "#bc8cff"
orange = "#f0883e"
red = "#b9543b"
yellow = "#c9a76e"
cyan = "#18a5b3"
purple = "#bc8cff"

# For now, shortcuts cannot have their own dedicated background
[colors.shortcut]
border = "colors.core.border"

[colors.text]
default = "colors.core.foreground"
muted = "#a8a29e"
danger = "#b9543b"
success = "#3a9c61"
placeholder = "{background.lighten(50%)}"
selection = { background = "{color9}", foreground = "{background}" }

[colors.text.links]
default = "#c9a76e"
visited = "#bc8cff"

[colors.input]
border = "{background}"
border_focus = "{color9}"
border_error = "#b9543b"

[colors.button.primary]
background = "{background.lighten(5%)}"
foreground = "{foreground}"
hover = {{ background = "{background.lighten(5%)}" }
focus = {{ outline = "colors.core.accent" }

[colors.list.item.hover]
foreground = "{foreground}"
secondary_foreground = "{foreground}"

[colors.list.item.selection]
background = "{background.lighten(5%)}"
foreground = "{foreground}"
secondary_background = "{background.lighten(5%)}"
secondary_foreground = "{foreground}"

[colors.grid.item]
background = "#15161b"
hover = { outline = "{foreground}" }
selection = { outline = "{foreground}" }

[colors.scrollbars]
background = "{background}"

[colors.loading]
bar = "{color9}"
spinner = "{foreground}"
