#!/usr/bin/env bash

# Import Current Theme
source "$HOME"/.config/rofi/applets/shared/theme.bash
theme="$type/$style"

# Theme Elements
status="`playerctl status`"
loop_status="`playerctl loop`"
shuffle_status="`playerctl shuffle`"
if [[ -z "$status" ]]; then
	prompt='Offline'
	mesg="Nothing is Playing"
else
	prompt="`playerctl metadata -f "{{artist}}" | sed "s/&/&amp;/g"`"
	mesg="`playerctl metadata -f "{{title}}" | sed "s/&/&amp;/g"` :: `playerctl metadata -f "{{album}}" | sed "s/&/&amp;/g"`"
fi

if [[ ( "$theme" == *'type-1'* ) || ( "$theme" == *'type-3'* ) || ( "$theme" == *'type-5'* ) ]]; then
	list_col='1'
	list_row='6'
elif [[ ( "$theme" == *'type-2'* ) || ( "$theme" == *'type-4'* ) ]]; then
	list_col='6'
	list_row='1'
fi

# Options
layout=`cat ${theme} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$layout" == 'NO' ]]; then
	if [[ ${status} == *"Playing"* ]]; then
		option_1=" Pause"
	else
		option_1=" Play"
	fi
	option_2=" Stop"
	option_3=" Previous"
	option_4=" Next"
	option_5=" Repeat"
	option_6=" Shuffle"
else
	if [[ ${status} == *"Playing"* ]]; then
		option_1=""
	else
		option_1=""
	fi
	option_2=""
	option_3=""
	option_4=""
	option_5=""
	option_6=""
fi

# Toggle Actions
active=''
urgent=''

# Repeat
if [[ ${loop_status} == "Playlist" ]]; then
    active="-a 4"
elif [[ ${loop_status} == "Track" ]]; then
    active="-a 4"
elif [[ ${loop_status} != "None" ]]; then
#     urgent="-u 4"
# else
    option_5=" Parsing Error"
fi

# Random
if [[ ${shuffle_status} == "On" ]]; then
    [ -n "$active" ] && active+=",5" || active="-a 5"
elif [[ ${shuffle_status} != "Off" ]]; then
#     [ -n "$urgent" ] && urgent+=",5" || urgent="-u 5"
# else
    option_6=" Parsing Error"
fi

# Rofi CMD
rofi_cmd() {
	rofi -theme-str "listview {columns: $list_col; lines: $list_row;}" \
		-theme-str 'textbox-prompt-colon {str: "";}' \
		-dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		${active} ${urgent} \
		-markup-rows \
		-theme ${theme}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		playerctl play-pause
        ;;
    $option_2)
		playerctl stop
        ;;
    $option_3)
		previous-song
        ;;
    $option_4)
		next-song
        ;;
    $option_5)
        if [[ ${loop_status} == "Playlist" ]]; then
            playerctl loop Track
        elif [[ ${loop_status} == "Track" ]]; then
            playerctl loop None
        elif [[ ${loop_status} == "None" ]]; then
            playerctl loop Playlist
        fi
        ;;
    $option_6)
		playerctl shuffle toggle
        ;;
esac
