#!/usr/bin/env bash
set -euo pipefail

if [[ -n "${DEBUG_MODE:-}" ]]; then
    set -x
fi

# Import Current Theme
theme=~/.config/rofi/styles/applets.rasi

# Theme Elements
status="$(media status)"
loop_status="$(media loop)"
shuffle_status="$(media shuffle)"
if [[ -z "$status" ]]; then
    prompt='Offline'
    mesg="Nothing is Playing"
else
    prompt="$(media metadata -f "{{artist}}" | sed "s/&/&amp;/g")"
    mesg="$(media metadata -f "{{title}}" | sed "s/&/&amp;/g") :: $(media metadata -f "{{album}}" | sed "s/&/&amp;/g")"
fi

list_col='6'
list_row='1'

# Options
if [[ ${status} == *"Playing"* ]]; then
    option_1=""
else
    option_1=""
fi
option_2=""
option_3=""
option_4=""
option_5=""
option_6=""

# Toggle Actions
active=''
urgent=''

# Repeat
if [[ ${loop_status} == "Playlist" ]]; then
    active="-a 4"
elif [[ ${loop_status} == "Track" ]]; then
    active="-a 4"
elif [[ ${loop_status} != "None" ]]; then
    #     urgent="-u 4"
    # else
    option_5=" Parsing Error"
fi

# Random
if [[ ${shuffle_status} == "On" ]]; then
    [ -n "$active" ] && active+=",5" || active="-a 5"
elif [[ ${shuffle_status} != "Off" ]]; then
    #     [ -n "$urgent" ] && urgent+=",5" || urgent="-u 5"
    # else
    option_6=" Parsing Error"
fi

# Rofi CMD
rofi_cmd() {
    rofi -theme-str "listview {columns: $list_col; lines: $list_row;}" \
        -theme-str 'textbox-prompt-colon {str: "";}' \
        -dmenu \
        -p "$prompt" \
        -mesg "$mesg" \
        ${active} ${urgent} \
        -markup-rows \
        -theme ${theme} \
        -kb-custom-1 "t" \
        -kb-custom-2 "s" \
        -kb-custom-3 "p" \
        -kb-custom-4 "n" \
        -kb-custom-5 "r" \
        -kb-custom-6 "h"
}

# Pass variables to rofi dmenu
run_rofi() {
    echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}

# Actions
chosen="$(run_rofi)"
code=$?

case ${code} in
10) media play-pause ;;
11) media stop ;;
12) media previous ;;
13) media next ;;
14) if [[ ${loop_status} == "Playlist" ]]; then
    media loop Track
elif [[ ${loop_status} == "Track" ]]; then
    media loop None
elif [[ ${loop_status} == "None" ]]; then
    media loop Playlist
fi ;;
15) media shuffle toggle ;;
esac
[[ $code == 0 ]] || exit

case ${chosen} in
$option_1) media play-pause ;;
$option_2) media stop ;;
$option_3) media previous ;;
$option_4) media next ;;
$option_5)
    if [[ ${loop_status} == "Playlist" ]]; then
        media loop Track
    elif [[ ${loop_status} == "Track" ]]; then
        media loop None
    elif [[ ${loop_status} == "None" ]]; then
        media loop Playlist
    fi
    ;;
$option_6) media shuffle toggle ;;
esac
