#!/usr/bin/env bash
set -euo pipefail

if [[ -n "${LOG:-}" ]]; then
    exec &>"/tmp/$(basename "$0").log"
    set -x
fi

if [[ -n "${DEBUG_MODE:-}" ]]; then
    set -x
fi

## Author  : Aditya Shakya (adi1090x)
## Github  : @adi1090x
#
## Applets : Power Menu

# Import Current Theme
theme=~/.config/rofi/styles/applets.rasi

# Theme Elements
prompt="$(uname -n)"
mesg="Uptime : $(uptime -p | sed -e 's/up //g')"

list_col='6'
list_row='1'

# Options
option_1=""
option_2=""
option_3=""
option_4=""
option_5=""
option_6=""
yes=''
no=''

# Rofi CMD
rofi_cmd() {
    rofi -theme-str "listview {columns: $list_col; lines: $list_row;}" \
        -theme-str 'textbox-prompt-colon {str: "";}' \
        -dmenu \
        -p "$prompt" \
        -mesg "$mesg" \
        -theme ${theme} \
        -markup-rows \
        -kb-custom-1 "l" \
        -kb-custom-2 "d" \
        -kb-custom-3 "s" \
        -kb-custom-4 "h" \
        -kb-custom-5 "r" \
        -kb-custom-6 "u"
}

# Pass variables to rofi dmenu
run_rofi() {
    echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}

# Confirmation CMD
confirm_cmd() {
    rofi -theme-str 'window {location: center; anchor: center; fullscreen: false; width: 350px;}' \
        -theme-str 'mainbox {orientation: vertical; children: [ "message", "listview" ];}' \
        -theme-str 'listview {columns: 2; lines: 1;}' \
        -theme-str 'element-text {horizontal-align: 0.5;}' \
        -theme-str 'textbox {horizontal-align: 0.5;}' \
        -dmenu \
        -p 'Confirmation' \
        -mesg 'Are you Sure?' \
        -theme ${theme}
}

# Ask for confirmation
confirm_exit() {
    echo -e "$yes\n$no" | confirm_cmd
}

# Confirm and execute
confirm_run() {
    selected="$(confirm_exit)"
    if [[ "$selected" == "$yes" ]]; then
        ${1}
        ${2}
    else
        exit
    fi
}

# Execute Command
run_cmd() {
    if [[ "$1" == '--opt1' ]]; then
        loginctl lock-session
    elif [[ "$1" == '--opt2' ]]; then
        confirm_run 'hyprctl dispatch exit'
    elif [[ "$1" == '--opt3' ]]; then
        confirm_run 'systemctl suspend'
    elif [[ "$1" == '--opt4' ]]; then
        confirm_run 'systemctl suspend'
    elif [[ "$1" == '--opt5' ]]; then
        confirm_run 'systemctl reboot'
    elif [[ "$1" == '--opt6' ]]; then
        confirm_run 'systemctl poweroff'
    fi
}

# Actions
chosen="$(run_rofi)"
code=$?

case ${code} in
10) run_cmd --opt1 ;;
11) run_cmd --opt2 ;;
12) run_cmd --opt3 ;;
13) run_cmd --opt4 ;;
14) run_cmd --opt5 ;;
15) run_cmd --opt6 ;;
esac
[[ $code == 0 ]] || exit

case ${chosen} in
$option_1) run_cmd --opt1 ;;
$option_2) run_cmd --opt2 ;;
$option_3) run_cmd --opt3 ;;
$option_4) run_cmd --opt4 ;;
$option_5) run_cmd --opt5 ;;
$option_6) run_cmd --opt6 ;;
esac
