#!/usr/bin/env bash

# Import Current Theme
theme=~/.config/rofi/styles/applets.rasi

# Theme Elements
prompt='Screenshot'
mesg=""

list_col='3'
list_row='1'

# Options
option_1="󰩬"
option_2="󰍹"
option_3=""

# Toggle Actions
# active='-a 1'
# urgent='-u 2'

# Rofi CMD
rofi_cmd() {
	rofi -theme-str "listview {columns: $list_col; lines: $list_row;}" \
		-theme-str 'textbox-prompt-colon {str: "󰹑";}' \
		-dmenu \
		-p "$prompt" \
		${active} ${urgent} \
		-markup-rows \
		-theme ${theme} \
        -kb-custom-1 "s" \
        -kb-custom-2 "m" \
        -kb-custom-3 "w"
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3" | rofi_cmd
}

# Actions
chosen="$(run_rofi)"
code=$?

case ${code} in
    10) screenshot;;
    11) screenshot monitor;;
    12) screenshot window;;
esac
[[ $code == 0 ]] || exit

case ${chosen} in
    $option_1) screenshot;;
    $option_2) screenshot monitor;;
    $option_3) screenshot window;;
esac
