version: "3.9"

services:
  zmk:
    container_name: zmk
    command: tail -f /dev/null
    restart: unless-stopped
    ports:
      - 3000
    build:
      context: .devcontainer/
      dockerfile: Dockerfile
    volumes:
      - ~/git/zmk:/workspace
      - ./root:/root
      - ./workspace/zephyr:/workspace/zephyr
      - ./workspace/modules:/workspace/modules
      - ./workspace/tools:/workspace/tools
